baseURL = "https://krawcuk.eu"

# set your your own ga token here.
#googleAnalytics = "UA/G-123123-12"

languageCode = "en-us"

# for using avicenna you need to set the themes to 'avicenna'
enableEmoji = true
theme = "avicenna"

# This is your page title, it appears in your tab
title = "Igor Krawczuk | Learning is Living"

# number of posts to show on the blog page
[pagination]
pagerSize = 10

[markup]
[markup.tableOfContents]
endLevel = 3
ordered = false
startLevel = 1

[params]
# it is used for the copy-right section of your page
name = "Igor Krawczuk"
sitestart = "2023"
